# Generated by Django 5.0.1 on 2024-01-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_tarea', '0003_remove_task_hour_completion_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hour_completion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='A mayor número, mayor prioridad.(El maximo es 3.)'),
        ),
    ]
