# Generated by Django 5.0.1 on 2024-01-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_contact', '0006_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
