# Generated by Django 5.0.1 on 2024-01-09 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_contact', '0008_alter_contact_cel_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img_contact',
            field=models.ImageField(blank=True, default='profile.png', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cel',
            field=models.CharField(help_text='Escribir el numero sin guiones(-).', max_length=12, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='<div class="alert alert-warning alert-dismissible fade show" role="alert"> Tu numero de telefono no es valido. <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>')]),
        ),
    ]
