# Generated by Django 5.0.1 on 2024-01-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_contact', '0011_alter_contact_img_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img_contact',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
