# Generated by Django 5.0.1 on 2024-01-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_contact', '0013_alter_contact_img_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='surnames',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
