# Generated by Django 5.0.1 on 2024-01-10 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_contact', '0020_alter_contact_img_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cel',
            field=models.CharField(help_text='Escribir el número sin guiones (-).', max_length=10, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='<div class="alert alert-warning alert-dismissible fade show" role="alert"> Tu número de teléfono no es válido. <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>')]),
        ),
    ]
